// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.19.6
// source: hero.proto

package hero

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	equip "heroServer/proto/rpcPb/equip"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type HeroType int32

const (
	HeroType_DEFAULT HeroType = 0
	HeroType_OFFENCE HeroType = 1 //攻击型
	HeroType_DEFENSE HeroType = 2 //防御
	HeroType_TREAT   HeroType = 3 //治疗
	HeroType_SHIELD  HeroType = 4 //护盾
)

// Enum value maps for HeroType.
var (
	HeroType_name = map[int32]string{
		0: "DEFAULT",
		1: "OFFENCE",
		2: "DEFENSE",
		3: "TREAT",
		4: "SHIELD",
	}
	HeroType_value = map[string]int32{
		"DEFAULT": 0,
		"OFFENCE": 1,
		"DEFENSE": 2,
		"TREAT":   3,
		"SHIELD":  4,
	}
)

func (x HeroType) Enum() *HeroType {
	p := new(HeroType)
	*p = x
	return p
}

func (x HeroType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HeroType) Descriptor() protoreflect.EnumDescriptor {
	return file_hero_proto_enumTypes[0].Descriptor()
}

func (HeroType) Type() protoreflect.EnumType {
	return &file_hero_proto_enumTypes[0]
}

func (x HeroType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HeroType.Descriptor instead.
func (HeroType) EnumDescriptor() ([]byte, []int) {
	return file_hero_proto_rawDescGZIP(), []int{0}
}

//数值类型
type NumericalValueType int32

const (
	NumericalValueType_NV_DEFAULT NumericalValueType = 0
	NumericalValueType_NV_OFFENCE NumericalValueType = 1 //攻击型
	NumericalValueType_NV_DEFENSE NumericalValueType = 2 //防御
	NumericalValueType_NV_SPEED   NumericalValueType = 3 //速度
	NumericalValueType_NV_TREAT   NumericalValueType = 4 //治疗
	NumericalValueType_NV_SHIELD  NumericalValueType = 5 //护盾
)

// Enum value maps for NumericalValueType.
var (
	NumericalValueType_name = map[int32]string{
		0: "NV_DEFAULT",
		1: "NV_OFFENCE",
		2: "NV_DEFENSE",
		3: "NV_SPEED",
		4: "NV_TREAT",
		5: "NV_SHIELD",
	}
	NumericalValueType_value = map[string]int32{
		"NV_DEFAULT": 0,
		"NV_OFFENCE": 1,
		"NV_DEFENSE": 2,
		"NV_SPEED":   3,
		"NV_TREAT":   4,
		"NV_SHIELD":  5,
	}
)

func (x NumericalValueType) Enum() *NumericalValueType {
	p := new(NumericalValueType)
	*p = x
	return p
}

func (x NumericalValueType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NumericalValueType) Descriptor() protoreflect.EnumDescriptor {
	return file_hero_proto_enumTypes[1].Descriptor()
}

func (NumericalValueType) Type() protoreflect.EnumType {
	return &file_hero_proto_enumTypes[1]
}

func (x NumericalValueType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NumericalValueType.Descriptor instead.
func (NumericalValueType) EnumDescriptor() ([]byte, []int) {
	return file_hero_proto_rawDescGZIP(), []int{1}
}

//数值
type NumericalValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  NumericalValueType `protobuf:"varint,1,opt,name=type,proto3,enum=hero.NumericalValueType" json:"type,omitempty"`
	Value uint64             `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"` //数值
}

func (x *NumericalValue) Reset() {
	*x = NumericalValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hero_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumericalValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumericalValue) ProtoMessage() {}

func (x *NumericalValue) ProtoReflect() protoreflect.Message {
	mi := &file_hero_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumericalValue.ProtoReflect.Descriptor instead.
func (*NumericalValue) Descriptor() ([]byte, []int) {
	return file_hero_proto_rawDescGZIP(), []int{0}
}

func (x *NumericalValue) GetType() NumericalValueType {
	if x != nil {
		return x.Type
	}
	return NumericalValueType_NV_DEFAULT
}

func (x *NumericalValue) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Hero struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             uint64            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UserId         uint64            `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	HeroType       HeroType          `protobuf:"varint,4,opt,name=heroType,proto3,enum=hero.HeroType" json:"heroType,omitempty"` //英雄类型
	NumericalValue []*NumericalValue `protobuf:"bytes,5,rep,name=numericalValue,proto3" json:"numericalValue,omitempty"`         //数值数据
	Equip          []*equip.Equip    `protobuf:"bytes,6,rep,name=equip,proto3" json:"equip,omitempty"`                           //装备
}

func (x *Hero) Reset() {
	*x = Hero{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hero_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hero) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hero) ProtoMessage() {}

func (x *Hero) ProtoReflect() protoreflect.Message {
	mi := &file_hero_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hero.ProtoReflect.Descriptor instead.
func (*Hero) Descriptor() ([]byte, []int) {
	return file_hero_proto_rawDescGZIP(), []int{1}
}

func (x *Hero) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Hero) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Hero) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Hero) GetHeroType() HeroType {
	if x != nil {
		return x.HeroType
	}
	return HeroType_DEFAULT
}

func (x *Hero) GetNumericalValue() []*NumericalValue {
	if x != nil {
		return x.NumericalValue
	}
	return nil
}

func (x *Hero) GetEquip() []*equip.Equip {
	if x != nil {
		return x.Equip
	}
	return nil
}

type GetUserHeroRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetUserHeroRequest) Reset() {
	*x = GetUserHeroRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hero_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserHeroRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserHeroRequest) ProtoMessage() {}

func (x *GetUserHeroRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hero_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserHeroRequest.ProtoReflect.Descriptor instead.
func (*GetUserHeroRequest) Descriptor() ([]byte, []int) {
	return file_hero_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserHeroRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserHeroResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age  uint32  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Hero []*Hero `protobuf:"bytes,3,rep,name=hero,proto3" json:"hero,omitempty"`
}

func (x *GetUserHeroResponse) Reset() {
	*x = GetUserHeroResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hero_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserHeroResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserHeroResponse) ProtoMessage() {}

func (x *GetUserHeroResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hero_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserHeroResponse.ProtoReflect.Descriptor instead.
func (*GetUserHeroResponse) Descriptor() ([]byte, []int) {
	return file_hero_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserHeroResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetUserHeroResponse) GetAge() uint32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *GetUserHeroResponse) GetHero() []*Hero {
	if x != nil {
		return x.Hero
	}
	return nil
}

var File_hero_proto protoreflect.FileDescriptor

var file_hero_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x68, 0x65, 0x72, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x68, 0x65,
	0x72, 0x6f, 0x1a, 0x0b, 0x65, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x54, 0x0a, 0x0e, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x2c, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x18, 0x2e, 0x68, 0x65, 0x72, 0x6f, 0x2e, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x61, 0x6c,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xd0, 0x01, 0x0a, 0x04, 0x48, 0x65, 0x72, 0x6f, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x08, 0x68, 0x65,
	0x72, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x68,
	0x65, 0x72, 0x6f, 0x2e, 0x48, 0x65, 0x72, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x68, 0x65,
	0x72, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3c, 0x0a, 0x0e, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x69,
	0x63, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x68, 0x65, 0x72, 0x6f, 0x2e, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x61, 0x6c, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x52, 0x0e, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x61, 0x6c, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x65, 0x71, 0x75, 0x69, 0x70, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x65, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x45, 0x71, 0x75, 0x69,
	0x70, 0x52, 0x05, 0x65, 0x71, 0x75, 0x69, 0x70, 0x22, 0x24, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x48, 0x65, 0x72, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x5b,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x48, 0x65, 0x72, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x68,
	0x65, 0x72, 0x6f, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x68, 0x65, 0x72, 0x6f,
	0x2e, 0x48, 0x65, 0x72, 0x6f, 0x52, 0x04, 0x68, 0x65, 0x72, 0x6f, 0x2a, 0x48, 0x0a, 0x08, 0x48,
	0x65, 0x72, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x45, 0x46, 0x41, 0x55,
	0x4c, 0x54, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x4f, 0x46, 0x46, 0x45, 0x4e, 0x43, 0x45, 0x10,
	0x01, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x45, 0x46, 0x45, 0x4e, 0x53, 0x45, 0x10, 0x02, 0x12, 0x09,
	0x0a, 0x05, 0x54, 0x52, 0x45, 0x41, 0x54, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x48, 0x49,
	0x45, 0x4c, 0x44, 0x10, 0x04, 0x2a, 0x6f, 0x0a, 0x12, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63,
	0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x4e,
	0x56, 0x5f, 0x44, 0x45, 0x46, 0x41, 0x55, 0x4c, 0x54, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x4e,
	0x56, 0x5f, 0x4f, 0x46, 0x46, 0x45, 0x4e, 0x43, 0x45, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x4e,
	0x56, 0x5f, 0x44, 0x45, 0x46, 0x45, 0x4e, 0x53, 0x45, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x4e,
	0x56, 0x5f, 0x53, 0x50, 0x45, 0x45, 0x44, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x56, 0x5f,
	0x54, 0x52, 0x45, 0x41, 0x54, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x56, 0x5f, 0x53, 0x48,
	0x49, 0x45, 0x4c, 0x44, 0x10, 0x05, 0x32, 0x53, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x48, 0x65, 0x72, 0x6f, 0x12, 0x44, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x48, 0x65, 0x72, 0x6f, 0x12, 0x18, 0x2e, 0x68, 0x65, 0x72, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x48, 0x65, 0x72, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x68, 0x65, 0x72, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x48, 0x65, 0x72,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x22, 0x5a, 0x20, 0x68,
	0x65, 0x72, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x72, 0x70, 0x63, 0x50, 0x62, 0x2f, 0x68, 0x65, 0x72, 0x6f, 0x3b, 0x68, 0x65, 0x72, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hero_proto_rawDescOnce sync.Once
	file_hero_proto_rawDescData = file_hero_proto_rawDesc
)

func file_hero_proto_rawDescGZIP() []byte {
	file_hero_proto_rawDescOnce.Do(func() {
		file_hero_proto_rawDescData = protoimpl.X.CompressGZIP(file_hero_proto_rawDescData)
	})
	return file_hero_proto_rawDescData
}

var file_hero_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_hero_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_hero_proto_goTypes = []interface{}{
	(HeroType)(0),               // 0: hero.HeroType
	(NumericalValueType)(0),     // 1: hero.NumericalValueType
	(*NumericalValue)(nil),      // 2: hero.NumericalValue
	(*Hero)(nil),                // 3: hero.Hero
	(*GetUserHeroRequest)(nil),  // 4: hero.GetUserHeroRequest
	(*GetUserHeroResponse)(nil), // 5: hero.GetUserHeroResponse
	(*equip.Equip)(nil),         // 6: equip.Equip
}
var file_hero_proto_depIdxs = []int32{
	1, // 0: hero.NumericalValue.type:type_name -> hero.NumericalValueType
	0, // 1: hero.Hero.heroType:type_name -> hero.HeroType
	2, // 2: hero.Hero.numericalValue:type_name -> hero.NumericalValue
	6, // 3: hero.Hero.equip:type_name -> equip.Equip
	3, // 4: hero.GetUserHeroResponse.hero:type_name -> hero.Hero
	4, // 5: hero.GetUserHero.GetUserHero:input_type -> hero.GetUserHeroRequest
	5, // 6: hero.GetUserHero.GetUserHero:output_type -> hero.GetUserHeroResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_hero_proto_init() }
func file_hero_proto_init() {
	if File_hero_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hero_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NumericalValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hero_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hero); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hero_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserHeroRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hero_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserHeroResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hero_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hero_proto_goTypes,
		DependencyIndexes: file_hero_proto_depIdxs,
		EnumInfos:         file_hero_proto_enumTypes,
		MessageInfos:      file_hero_proto_msgTypes,
	}.Build()
	File_hero_proto = out.File
	file_hero_proto_rawDesc = nil
	file_hero_proto_goTypes = nil
	file_hero_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GetUserHeroClient is the client API for GetUserHero service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GetUserHeroClient interface {
	GetUserHero(ctx context.Context, in *GetUserHeroRequest, opts ...grpc.CallOption) (*GetUserHeroResponse, error)
}

type getUserHeroClient struct {
	cc grpc.ClientConnInterface
}

func NewGetUserHeroClient(cc grpc.ClientConnInterface) GetUserHeroClient {
	return &getUserHeroClient{cc}
}

func (c *getUserHeroClient) GetUserHero(ctx context.Context, in *GetUserHeroRequest, opts ...grpc.CallOption) (*GetUserHeroResponse, error) {
	out := new(GetUserHeroResponse)
	err := c.cc.Invoke(ctx, "/hero.GetUserHero/GetUserHero", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetUserHeroServer is the server API for GetUserHero service.
type GetUserHeroServer interface {
	GetUserHero(context.Context, *GetUserHeroRequest) (*GetUserHeroResponse, error)
}

// UnimplementedGetUserHeroServer can be embedded to have forward compatible implementations.
type UnimplementedGetUserHeroServer struct {
}

func (*UnimplementedGetUserHeroServer) GetUserHero(context.Context, *GetUserHeroRequest) (*GetUserHeroResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserHero not implemented")
}

func RegisterGetUserHeroServer(s *grpc.Server, srv GetUserHeroServer) {
	s.RegisterService(&_GetUserHero_serviceDesc, srv)
}

func _GetUserHero_GetUserHero_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserHeroRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetUserHeroServer).GetUserHero(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hero.GetUserHero/GetUserHero",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetUserHeroServer).GetUserHero(ctx, req.(*GetUserHeroRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GetUserHero_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hero.GetUserHero",
	HandlerType: (*GetUserHeroServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserHero",
			Handler:    _GetUserHero_GetUserHero_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hero.proto",
}
